SRC += kohibin.c 
VPATH  +=  keyboards/gboards/

MOUSEKEY_ENABLE = yes       # Mouse keys
UNICODE_ENABLE = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
CAPS_WORD_ENABLE = no
COMMAND_ENABLE = no
SWAP_HANDS_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no